SELECT atr.brand                              AS brand,
       atr.brand_id                           AS brand_id,
       atr.category                           AS category,
       atr.sub_category                       AS sub_category,
       atr.channel                            AS channel,
       atr.skuid                              AS skuid,
       atr.product_id                         AS product_id,
       atr.key                                AS attr_key,
       Avg(Cast(atr.value AS DECIMAL(10, 2))) AS attr_value,
       to_timestamp(atr.year || '-' || atr.month  || '-' || atr.day  || ' 00:00:00', 'YYYY-MM-DD HH24:MI:SS') as ts,
       atr.year,
       atr.month,
       atr.day,
       CURRENT_DATE as current_date
FROM rnr_spectrum_prod.attribute atr
GROUP  BY atr.brand,
          atr.brand_id,
          atr.category,
          atr.sub_category,
          atr.channel,
          atr.skuid,
          atr.product_id,
          atr.key,
          atr.year,
          atr.month,
          atr.day
